APP_ID = debug_app
APP_VERSION = 0.1
APP_SDK_ROOT = ../..
APP_TARGET = f7
APP_FAP_CATEGORY = Debug
APP_FAP_DEBUG = debug_app.c
APP_FAP_ICON = A_Debugging_10x10

include $(APP_SDK_ROOT)/include.mk

CFLAGS += -Wno-unused-function